[package]
name = "syrup-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preserves = "4.994.0"
serde = "1.0.197"
winnow = "0.6.3"
